[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
bencher = { version = "2.7.2", package = "codspeed-bencher-compat" }

[[bench]]
name = "bench"
harness = false
path = "."
